---
annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: added
      description: Made chart available through OCI repository
apiVersion: v2
appVersion: "v0.8.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.31.3
description: A chart to run Terralist (terralist.io) running on kubernetes
home: https://terralist.io/
icon: https://raw.githubusercontent.com/terralist/terralist/refs/heads/master/docs/assets/terralist.svg
keywords:
  - terraform
  - providers
  - module
  - registry
  - terralist
maintainers:
  - name: barnes-c
    email: 68067715+barnes-c@users.noreply.github.com
  - name: valentindeaconu
    email: 88654883+valentindeaconu@users.noreply.github.com
name: terralist
sources:
  - https://github.com/terralist/helm-charts/tree/main/charts/terralist
  - https://github.com/terralist/terralist
version: 0.8.0
