---
## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s-labs/helm-charts/tree/923ef40a39520979c98f354ea23963ee54f54433/charts/library/common
## Refer there for more detail about the supported values

# These entries are shared between all the Terralist components

env:

image:
  tag: v0.8.0

terralist:
  metrics:
    # Enabling this will create the service monitors needed to monitor terralist with the prometheus operator
    enabled: false
  persistence:
    # Main data store for all providers and modules.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim:

server:
  enabled: true
  controller:
    type: deployment
  image:
    repository: ghcr.io/terralist/terralist
    tag: v0.8.0
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: terralist.local
          paths:
            - path: "/"
      tls: []
