apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.podLabels "context" .) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
  selector:
    {{- include "common.labels.matchLabels" (dict "customLabels" .Values.podLabels "context" .) | nindent 4 }}
