name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: get latest release
        id: version
        run: |
          tag=$(curl -s https://api.github.com/repos/terralist/terralist/releases/latest | jq '.tag_name' -r)
          chart_version=$(yq '.version' charts/terralist/Chart.yaml)
          if [[ "$chart_version" != "${tag#terralist-}" ]]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: run chart-releaser
        id: cr
        if: ${{ steps.version.outputs.should_release == 'true' }}
        uses: helm/chart-releaser-action@v1.8.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true

      - name: Login to GitHub Container Registry
        if: ${{ steps.version.outputs.should_release == 'true' }}
        uses: docker/login-action@3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.version.outputs.should_release == 'true' }}
        name: Push Chart
        run: helm push .cr-release-packages/terralist-*.tgz oci://ghcr.io/${{ github.repository }}
